# Generated by Django 4.2.4 on 2023-08-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_location_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardealer',
            name='location',
        ),
        migrations.AddField(
            model_name='cardealer',
            name='location',
            field=models.ManyToManyField(to='home.location'),
        ),
    ]
