# Generated by Django 4.2.4 on 2023-08-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_cardealer_phone'),
        ('home', '0009_remove_cardealer_location_cardealer_location'),
    ]

    operations = [
    ]
